project:
  type: website
  output-dir: docs

website:
  title: "Jiregna Olani Kedida"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: lab.qmd
        text: Lab Vision
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: training.qmd
        text: Training
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css